In [5]:
import numpy as np
import pandas as pd

Data comes in all sizes and shapes and formats, and we will spend lots of our time <b>wrangling</b> the data into the format we could use. Wrangling is a topic for another day; for now all data sets will be tidy right away.

<h2>The data set</h2>

The data file is a <b>CSV file</b>(comma-separated value). It is a text file that is easily read into data structures in many programming languages. When storing data, we should try to always store it in such a format which is open, has a well-defined specification, and is readable in many contexts.
<ul>
    <li><b>Good formats: </b> JSON, CSV</li>
    <li><b>Bad formats: </b> Excel, <code>.mat</code></li>
</ul>

In [6]:
!head ../data/gfmt_sleep.csv #taking a peek!

While we could write a parser for this file, since it is in a CSV format we could use pre-built tools. For this we may use <b>Pandas</b>, a <b>powerful</b> tool for handling data.
<h2>Pandas</h2>
The primary object of Pandas is the <code>DataFrame</code>. We will use Pandas to read data and store it into <code>DataFrame</code> instance.

In [7]:
df = pd.read_csv('../data/gfmt_sleep.csv', na_values='*')

In [8]:
# Look at the contents of first 5 rows:
df.head()

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence incorrect hit,confidence correct reject,confidence incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess
0,8,f,39,65,80,72.5,91.0,90.0,93.0,83.5,93.0,90.0,9,13,2
1,16,m,42,90,90,90.0,75.5,55.5,70.5,50.0,75.0,50.0,4,11,7
2,18,f,31,90,95,92.5,89.5,90.0,86.0,81.0,89.0,88.0,10,9,3
3,22,f,35,100,75,87.5,89.5,NaN,71.0,80.0,88.0,80.0,13,8,20
4,27,f,74,60,65,62.5,68.5,49.0,61.0,49.0,65.0,49.0,13,9,12

<code>DataFrame</code> is always indexed by columns, with column names(<code>string</code> values) being the keys.

In [18]:
df['percent correct'].head()

0    72.5
1    90.0
2    92.5
3    87.5
4    62.5
Name: percent correct, dtype: float64

To refer to a particular element of the column we can use integer indexes.

In [19]:
df['percent correct'][4]

62.5

However, this is <b>not</b> the preferred way to do this. It is better to use <code>loc</code> method:

In [20]:
df.loc[4, 'percent correct']

62.5

<b>Row indices need not be integers</b>, and we should not count on that. In practice, almost always we will use <b>boolean indexing</b>.

In [21]:
# Get the value(s) in the column 'percent correct' with the value in 'participant number' 42
df.loc[df['participant number'] == 42, 'percent correct']

54    85.0
Name: percent correct, dtype: float64

In [22]:
# Get the entire row about participant with number 42
df.loc[df['participant number'] == 42, :]

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence incorrect hit,confidence correct reject,confidence incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess
54,42,m,29,100,70,85.0,75.0,NaN,64.5,43.0,74.0,43.0,32,1,6

We can use boolean bitwise operators in the boolean indexing. <code>&</code> for bitwise AND, <code>|</code> for bitwise OR, <code>~</code> for bitwise NOT.

In [23]:
# Get entries for women under 21
df.loc[(df['age'] < 21) & (df['gender'] == 'f'), :]

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence incorrect hit,confidence correct reject,confidence incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess
27,3,f,16,70,80,75.0,70.0,57.0,54.0,53.0,57.0,54.5,23,1,3
29,5,f,18,90,100,95.0,76.5,83.0,80.0,NaN,80.0,83.0,21,7,5
66,58,f,16,85,85,85.0,55.0,30.0,50.0,40.0,52.5,35.0,29,2,11
79,72,f,18,80,75,77.5,67.5,51.5,66.0,57.0,67.0,53.0,29,4,6
88,85,f,18,85,85,85.0,93.0,92.0,91.0,89.0,91.5,91.0,25,4,21

In [24]:
# We create three boolean arrays, and for each the entries are True if and only if the
# Boolean statement evaluated at the identical cell at the expression on the right is True
# and False otherwise

under30 = df['age'] < 30
women = df['gender'] == 'f'
good_performers = df['percent correct'] > 85

In [25]:
# Get the entries of Women under 30 who performed good on the face matching test
df.loc[under30 & women & good_performers, :]

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence incorrect hit,confidence correct reject,confidence incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess
22,93,f,28,100,75,87.5,89.5,NaN,67.0,60.0,80.0,60.0,16,7,4
29,5,f,18,90,100,95.0,76.5,83.0,80.0,NaN,80.0,83.0,21,7,5
30,6,f,28,95,80,87.5,100.0,85.0,94.0,61.0,99.0,65.0,19,7,12
33,10,f,25,100,100,100.0,90.0,NaN,85.0,NaN,90.0,NaN,17,10,11
56,44,f,21,85,90,87.5,66.0,29.0,70.0,29.0,67.0,29.0,26,7,18
58,48,f,23,90,85,87.5,67.0,47.0,69.0,40.0,67.0,40.0,18,6,8
60,51,f,24,85,95,90.0,97.0,41.0,74.0,73.0,83.0,55.5,29,1,7
75,67,f,25,100,100,100.0,61.5,NaN,58.5,NaN,60.5,NaN,28,8,9

This would normally require us to use loops, but the numpy and pandas libraries allow us to treat all this as simple non-loop operations.

In [26]:
# initialize the list of Boolean indices
indices = [False] * len(df)

# Iterate over the rows of the DataFrame to check if the row should be included
for i, r in df.iterrows():
    if r['age'] < 30 and r['gender'] == 'f' and r['percent correct'] > 85:
        indices[i] = True

#Make our selection with Boolean indexing
df.loc[indices, :]

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence incorrect hit,confidence correct reject,confidence incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess
22,93,f,28,100,75,87.5,89.5,NaN,67.0,60.0,80.0,60.0,16,7,4
29,5,f,18,90,100,95.0,76.5,83.0,80.0,NaN,80.0,83.0,21,7,5
30,6,f,28,95,80,87.5,100.0,85.0,94.0,61.0,99.0,65.0,19,7,12
33,10,f,25,100,100,100.0,90.0,NaN,85.0,NaN,90.0,NaN,17,10,11
56,44,f,21,85,90,87.5,66.0,29.0,70.0,29.0,67.0,29.0,26,7,18
58,48,f,23,90,85,87.5,67.0,47.0,69.0,40.0,67.0,40.0,18,6,8
60,51,f,24,85,95,90.0,97.0,41.0,74.0,73.0,83.0,55.5,29,1,7
75,67,f,25,100,100,100.0,61.5,NaN,58.5,NaN,60.5,NaN,28,8,9

<code>df.iterrows()</code> creates an iterator over the rows of the <code>DataFrame</code>. As we can see, <code>DataFrame</code> is a powerful tool that allows us to do all that looping without worrying about the implementation, while keeping the readability to maximum. The iterator itself is rarely used, but there may be cases when it is needed. As we will see now, most of the times we can just do calculations on <code>DataFrame</code> directly.

<h2>Calculating with data frames</h2>
Test subject is said to have insomnia if they have an SCI of 16 at most. We might want to add a column that explicitly says if the subject has insomnia.

In [27]:
(df['sci'] <= 16) # --- Create a boolean column that is true if and only if the subject for
                  #     whom the row corresponds has insomnia.

0       True
1       True
2       True
3       True
4       True
       ...
97     False
98     False
99     False
100    False
101    False
Name: sci, Length: 102, dtype: bool

In [28]:
# Create a column with the name "insomnia" which is the Boolean column cell of which are 
# True if and only if the SCI of the subject is at most 16, and False otherwise.
df['insomnia'] = df['sci'] <= 16

# Taking a peek!
df.head()

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence incorrect hit,confidence correct reject,confidence incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess,insomnia
0,8,f,39,65,80,72.5,91.0,90.0,93.0,83.5,93.0,90.0,9,13,2,True
1,16,m,42,90,90,90.0,75.5,55.5,70.5,50.0,75.0,50.0,4,11,7,True
2,18,f,31,90,95,92.5,89.5,90.0,86.0,81.0,89.0,88.0,10,9,3,True
3,22,f,35,100,75,87.5,89.5,NaN,71.0,80.0,88.0,80.0,13,8,20,True
4,27,f,74,60,65,62.5,68.5,49.0,61.0,49.0,65.0,49.0,13,9,12,True

Applying <code><=</code> operator to a <code>Series</code> resulted in <b>elementwise</b> application. This is called <strong>vectorization</strong>. Just like with numpy arrays, we can apply numpy functions to Pandas objects:

In [42]:
print('Insomniacs:', np.mean(df.loc[df['insomnia'], 'percent correct']))
print('Control:', np.mean(df.loc[~df['insomnia'], 'percent correct']))

Insomniacs: 76.1
Control: 81.46103896103897

In [44]:
# DataFrame.describe method computes for us all the summary statistics we usually need
# for each column
df.describe()

,participant number,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence incorrect hit,confidence correct reject,confidence incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess
count,102.000000,102.000000,102.000000,102.000000,102.000000,102.000000,84.000000,102.000000,93.000000,102.000000,99.000000,102.000000,102.000000,102.000000
mean,52.049020,37.921569,83.088235,77.205882,80.147059,74.990196,58.565476,71.137255,61.220430,74.642157,61.979798,22.245098,5.274510,7.294118
std,30.020909,14.029450,15.091210,17.569854,12.047881,14.165916,19.560653,14.987479,17.671283,13.619725,15.921670,7.547128,3.404007,4.426715
min,1.000000,16.000000,35.000000,20.000000,40.000000,29.500000,7.000000,19.000000,17.000000,24.000000,24.500000,0.000000,0.000000,0.000000
25%,26.250000,26.500000,75.000000,70.000000,72.500000,66.000000,46.375000,64.625000,50.000000,66.000000,51.000000,17.000000,3.000000,4.000000
50%,52.500000,36.500000,90.000000,80.000000,83.750000,75.000000,56.250000,71.250000,61.000000,75.750000,61.500000,23.500000,5.000000,7.000000
75%,77.750000,45.000000,95.000000,90.000000,87.500000,86.500000,73.500000,80.000000,74.000000,82.375000,73.000000,29.000000,7.000000,10.000000
max,103.000000,74.000000,100.000000,100.000000,100.000000,100.000000,92.000000,100.000000,100.000000,100.000000,100.000000,32.000000,15.000000,21.000000

<code>describe</code> is also a Pandas <code>DataFrame</code>, so we can use indexing, everything we did with <code>DataFrame</code>'s so far on it:

In [10]:
# Get the median for every column in df
df.describe().loc['50%', :]

participant number             52.50
age                            36.50
correct hit percentage         90.00
correct reject percentage      80.00
percent correct                83.75
confidence when correct hit    75.00
confidence incorrect hit       56.25
confidence correct reject      71.25
confidence incorrect reject    61.00
confidence when correct        75.75
confidence when incorrect      61.50
sci                            23.50
psqi                            5.00
ess                             7.00
Name: 50%, dtype: float64

<h2>Slicing with iloc</h2>

Letâs say we wanted to consider only the males in the study. We can slice them out and put them in a new data frame (actually a view into the existing data frame df) using Boolean indexing.

In [12]:
df_males = df.loc[df['gender'] == 'm', :]

df_males.head()

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence incorrect hit,confidence correct reject,confidence incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess
1,16,m,42,90,90,90.0,75.5,55.5,70.5,50.0,75.0,50.0,4,11,7
6,30,m,32,90,75,82.5,67.0,56.5,66.0,65.0,66.0,64.0,16,9,3
7,33,m,62,45,90,67.5,54.0,37.0,65.0,81.5,62.0,61.0,14,9,9
18,78,m,31,100,70,85.0,92.0,NaN,81.0,60.0,87.5,60.0,14,6,11
19,80,m,28,100,50,75.0,100.0,NaN,100.0,100.0,100.0,100.0,12,7,12

Note that the numbers of rows are here from the original <code>df</code>, and not 1, 2, 3, 4, 5... This is actually not too bad, since the row indices need not be integers! There is however a way to index through rows and columns by integers:

In [14]:
# Accessing "third" row and "zeroth" column with iloc
df_males.iloc[3, 0]

78

However, we may be relying here on the <code>DataFrame</code> being sorted in a particular order, which is never a good practice. So, in reality we should never need to use <code>iloc</code>. <strong>Only</strong> use it when the order is irrelevant.

<h2>Renaming columns</h2>

Truth be told, sci, psqi, ess do not tell much us without knowing what these abbreviations stand for. <i>Explicit <b>is</b> better than Implicit</i>, so let us make these column names longer:

In [17]:
# We need to make a renaming dictionary:
rename_dict = {
    "ess": "Epworth Sleepiness Scale",
    "sci": "Sleep Condition Indicator",
    "psqi": "Pittsburgh Sleep Quality Index",
}

# Rename the columns by calling the renaming dictionary
df = df.rename(columns=rename_dict)

df.head()

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence incorrect hit,confidence correct reject,confidence incorrect reject,confidence when correct,confidence when incorrect,Sleep Condition Indicator,Pittsburgh Sleep Quality Index,Epworth Sleepiness Scale
0,8,f,39,65,80,72.5,91.0,90.0,93.0,83.5,93.0,90.0,9,13,2
1,16,m,42,90,90,90.0,75.5,55.5,70.5,50.0,75.0,50.0,4,11,7
2,18,f,31,90,95,92.5,89.5,90.0,86.0,81.0,89.0,88.0,10,9,3
3,22,f,35,100,75,87.5,89.5,NaN,71.0,80.0,88.0,80.0,13,8,20
4,27,f,74,60,65,62.5,68.5,49.0,61.0,49.0,65.0,49.0,13,9,12

Boolean indexing comes with a payoff, as it is essentially building a boolean array and reverse dictionary look-up for every <code>True</code> value, while non-boolean indexing is just a constant operation.

In [18]:
print("Boolean indexing(slow):")
%timeit df.loc[df['participant number'] == 42, 'percent correct']

print("\nDirect indexing(fast):")
%timeit df.loc[54, 'percent correct']

Boolean indexing(slow):
59.2 Âµs Â± 696 ns per loop (mean Â± std. dev. of 7 runs, 10,000 loops each)

Direct indexing(fast):
3.34 Âµs Â± 32.9 ns per loop (mean Â± std. dev. of 7 runs, 100,000 loops each)